### PR TITLE
TST: Update for pytest 7

### PR DESCRIPTION
**Pull request by StefRe**
Remove 36 PytestRemovedIn8Warning and PytestReturnNotNoneWarning warnings.

### CODE REVIEW

**Comment by StefRe** [comment]
Python 3.5 and 3.6 are no longer supported by `ubuntu-latest` (22.04) on Github workflows.

**Comment by phobson** [comment]
@StefRe thanks for the update! I can take a look at this soon

**Comment by phobson** [comment]
@StefRe -- anything else you think should go in here?

**Comment by StefRe** [comment]
> @StefRe -- anything else you think should go in here?

no, looks good to me

**Comment by StefRe** [comment]
I only now saw that all the tests are run twice: first in [Basic unit tests](https://github.com/matplotlib/mpl-probscale/blob/master/.github/workflows/python-runtests-basic.yml) and then in [Image comparison tests](https://github.com/matplotlib/mpl-probscale/blob/master/.github/workflows/python-runtests-img-comp.yml). The latter installs `pytest-mpl` and hence runs without warnings. Both workflows run, however, the _complete_ test suite. What is actually the idea behind splitting the tests into two workflows?

**Comment by phobson** [comment]
> What is actually the idea behind splitting the tests into two workflows?

I'm sure I had a reason at the time. Maybe the img tests were flaky and allowed to fail? In any case, I can't think of a good reason now.

**Comment by phobson** [comment]
Oh also the img tests are only run on the "latest" version of python, not e.g., 3.8, 3.9, etc. Maybe that should change

**Comment by StefRe** [comment]
My point was that [Basic unit tests](https://github.com/matplotlib/mpl-probscale/blob/master/.github/workflows/python-runtests-basic.yml) and [Image comparison tests](https://github.com/matplotlib/mpl-probscale/blob/master/.github/workflows/python-runtests-img-comp.yml) do the same thing, i.e. all tests are run twice (even more so now that the python version matrices are identical). So if we want to run the image comparison tests separately then maybe it's clearer to add `-m "not mpl_image_compare"` to `python check_probscale.py --doctest-modules` in [python-runtests-basic.yml](https://github.com/matplotlib/mpl-probscale/blob/master/.github/workflows/python-runtests-basic.yml) and `-m mpl_image_compare` to `python check_probscale.py --mpl --doctest-modules` in [python-runtests-img-comp.yml](https://github.com/matplotlib/mpl-probscale/blob/master/.github/workflows/python-runtests-img-comp.yml), respectively.

**Comment by phobson** [comment]
Yeah I agree. Since all python versions in the img-comp matrix are passing, I'd be inclined to scrap the "vanilla" tests altogether.

**Pull request merged**
